// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqxhssisrnzgkmrzlyip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeGhzc2lzcm56Z2ttcnpseWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMzcwNjIsImV4cCI6MjA4OTYxMzA2Mn0.QNpmln2-gsW7An_RLOmesLRzFW_y9ADU5ZiMuH18R8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});